### ISSUE TITLE
Docker Networking Issue

### ISSUE THREAD

**Issue by Patilrakesh1998** [ramlaxman/container-scheduling-openstack#1]
I am using MySQL and WordPress containers for Docker Containers Networking. After successfully pulling containers from Docker Hub, I had launch both the containers .
But the localhost:8080 is not working for this. Assigning 8080 as open port for this networking the localhost:8080 link in the web browser is showing "This site can’t be reached". 

Referred Video Link: https://www.youtube.com/watch?v=HY3WDz6j_hU&t=700s

I had also tried with nginx web server for web application launch, but the same issue arises.
![localhost_issue8080](https://user-images.githubusercontent.com/34189979/69495878-fc3d3b80-0ef1-11ea-9819-7d9c207d87dc.PNG)

**Comment by ramlaxman** [comment]
Hello @Patilrakesh1998 ,
Kindly google the problem.  You need to use IP address as windows is unable to resolve DNS. 
Also try to use new command instead of --link.

**Comment by Patilrakesh1998** [comment]
> Hello @Patilrakesh1998 ,
> Kindly google the problem. You need to use IP address as windows is unable to resolve DNS.
> Also try to use new command instead of --link.

Sure Sir I will check it out the corrections
