### ISSUE TITLE
Not able to build container for python 2 using python 2 image used from Docker Hub

### ISSUE THREAD

**Issue by Patilrakesh1998** [ramlaxman/container-scheduling-openstack#3]
******************************************************
FROM python:2
WORKDIR /usr/src/app
RUN pip install MySQL-python
COPY . .
CMD [ "python", "./script.py" ]
******************************************************
The above code is written in the created docker file.

**---> The working directory is D**

The below mentioned text is the error occured while building the image.

### **_unable to prepare context: unable to evaluate symlinks in Dockerfile path: CreateFile D:\FINAL_YEAR\MYSQL_DATABASE_AND_PYTHON\Dockerfile: The system cannot find the file specified._**

**Comment by ramlaxman** [comment]
dockerfile or docker commands work on directory. All you need to do it to put dockerfile inside folder and then try the docker build it will work. If still not sure about it, you can find details here:

https://stackoverflow.com/questions/35511604/docker-unable-to-prepare-context-unable-to-evaluate-symlinks-in-dockerfile-pat/53734661#53734661

**Comment by Patilrakesh1998** [comment]
Still not resolved Sir. I had putted it in the above mention directory ( e.g. D:\FINAL_YEAR\MYSQL_DATABASE_AND_PYTHON ). 
I am also little bit confused about **why it is searching for Dockerfile in the current working directory**. The name given to the docker file is **my-script**

**Comment by ramlaxman** [comment]
This is the actual problem. You should not rename dockerfile. It must be `dockerfile `; instead change the directory name but never ever change name of `dockerfile`. Hope this helps.

**Comment by Patilrakesh1998** [comment]
Yes Sir it helps...Thank You Sir
